import Footer from "@/components/footer";
import NAV from "@/components/nav";
import Questions from "@/components/questions";
import Head from "next/head";

const FAQ: React.FC = () => {
  return (
    <>
      <Head>
        <title>envious | faq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full flex flex-col justify-between items-center bg-slate-900">
        <NAV />
        <Questions />
        <Footer />
      </div>
    </>
  );
};

export default FAQ;
