import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [imgB64, setImgB64] = useState<string>("");
  const [prevTime, setPrev] = useState(Date.now());
  const [count, setCount] = useState(0);
  const [fps, setFPS] = useState(0);

  const ws_endpoint = "ws://192.168.128.90:5000/";

  useEffect(() => {
    const ws = new WebSocket(ws_endpoint);

    ws.onopen = () => {
      console.log("handshake successful [listener]");
      ws.send("READY");

      ws.onmessage = (img) => {
        setImgB64(img.data);
        ws.send("READY");
      };
    };

    ws.onclose = () => {
      console.log("disconnected [listener]");
    };
  }, []);

  // FPS tracker
  useEffect(() => {
    setCount(count + 1);
    if (Date.now() - prevTime > 1000) {
      setFPS(count);
      setPrev(Date.now());
      setCount(0);
    }
  }, [imgB64]);

  return (
    <>
      <Head>
        <title>Video Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-900 w-full h-full flex justify-center items-center">
        <h1 className="absolute top-0 right-0 bg-black">FPS: {fps}</h1>
        <img
          src={imgB64}
          className="w-full h-full"
          alt="live image from rasPi"
        />
      </main>
    </>
  );
}
