import Head from "next/head";
import Slider from "@/components/slider";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  // states to track curr image
  const [imgB64, setImgB64] = useState<string>("");

  // states to track fps
  const [prevTime, setPrev] = useState(Date.now());
  const [count, setCount] = useState(0);
  const [fps, setFPS] = useState(0);

  // states to track motor
  const [RMotor, setRMotor] = useState<number>(0);
  const [LMotor, setLMotor] = useState<number>(0);
  const motorRef = useRef({ LMotor, RMotor });

  const ws_endpoint = "ws://192.168.128.90:5000/";

  interface ws_msg {
    type: "MOTOR" | "CAM";
    RMotor?: number;
    LMotor?: number;
  }

  // get cam feeds
  useEffect(() => {
    const ws = new WebSocket(ws_endpoint);

    ws.onopen = () => {
      const cdata: ws_msg = { type: "CAM" };

      console.log("handshake successful [listener]");
      ws.send(JSON.stringify(cdata));

      ws.onmessage = (img) => {
        const mdata: ws_msg = { type: "MOTOR", ...motorRef.current };
        setImgB64(img.data);

        ws.send(JSON.stringify(mdata));
        ws.send(JSON.stringify(cdata));
      };
    };

    ws.onclose = () => {
      console.log("disconnected [listener]");
    };
  }, []);

  // FPS tracker
  useEffect(() => {
    setCount(count + 1);
    if (Date.now() - prevTime > 1000) {
      setFPS(count);
      setPrev(Date.now());
      setCount(0);
    }
  }, [imgB64]);

  // motor value ref update on state change
  useEffect(() => {
    motorRef.current = {
      LMotor,
      RMotor,
    };
  }, [RMotor, LMotor]);

  return (
    <>
      <Head>
        <title>Video Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-900 w-full h-full flex justify-evenly items-center">
        <Slider value={LMotor} setValue={setLMotor} />
        <h1 className="absolute bottom-0 bg-slate-900 px-4 m-4 rounded-full">
          FPS: {fps}
        </h1>
        <img
          src={imgB64}
          className="p-3 rounded-3xl h-full"
          alt="live image from rasPi"
        />
        <Slider value={RMotor} setValue={setRMotor} />
      </main>
    </>
  );
}
